Delivery/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.index, name='Del_index'),
    path('signup/', views.signup, name='Del_signup'),
    path('profile/', views.profile_page, name='Del_profile'),
    path('ajax/load-areas/', views.load_areas, name='Del_ajax_load_areas'),
    re_path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='Del_activate'),
    path('del_orders/', views.del_orders, name='Del_orders'),
    path('edit/', views.edit_profile, name='Del_edit_profile'),
]

R_m/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('Res_Man.urls')),
]

Res_Man/urls.py
from django.contrib import admin
from django.urls import path
from R_m import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('snippets/', views.snippet_list),
    path('snippets/<int:pk>/', views.snippet_detail),

]

search/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('S_search/', include('S_search.urls', namespace='S_search')),
]

Customers/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator
from django.db import models
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField

from Delivery.models import Delivery
from Restaurants.models import Restaurant, FoodCategory, Food

# Create your models here.

areas = (('Cunninghum Road', 'Cunninghum Road'),
         ('Frazer Town', 'Frazer Town'),
         ('Whitefield', 'Whitefield'),
         ('Church Street', 'Church Street'),
         ('Egmore', 'Egmore'),
         ('Thirumalai', 'Thirumalai'),
         ('Anna Salai', 'Anna Salai'),
         ('Mount Road', 'Mount Road'),
         ('Connaught Place', 'Connaught Place'),
         ('Green Park', 'Green Park'),
         ('Nehru Road', 'Nehru Road'),
         ('Golf Course Road', 'Golf Course Road'),
         ('Park Street', 'Park Street'),
         ('Meredith Street', 'Meredith Street'),
         ('Chittaranjan Avenue', 'Chittaranjan Avenue'),
         ('S.N. Banerjee Road', 'S.N. Banerjee Road'),)

Cities = (('Bangalore', 'Bangalore'),
          ('Chennai', 'Chennai'),
          ('Delhi', 'Delhi'),
          ('Kolkata', 'Kolkata'),
          )

States = (('Karnataka', 'Karnataka'),
          ('Tamil Nadu', 'Tamil Nadu'),
          ('Delhi', 'Delhi'),
          ('West Bengal', 'West Bengal'),
          )


class Profile(models.Model):
    Customer_ID = models.AutoField(primary_key=True, auto_created=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Customer_First_Name = models.CharField(max_length=200)
    Customer_Last_Name = models.CharField(max_length=200)
    Customer_Phone_Number = PhoneNumberField(max_length=13)
    Customer_Picture = models.ImageField(upload_to='media',
                                         default='media/default_res.jpg')
    Customer_Email = models.EmailField(default="asd@rew.com")

    def __str__(self):
        return self.user.username


class City(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Area(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Address(models.Model):
    Address_ID = models.AutoField(primary_key=True)
    Customer_ID = models.ForeignKey(Profile, on_delete=models.CASCADE)
    Home = models.CharField(max_length=250)
    Street = models.CharField(max_length=250)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    area = models.ForeignKey(Area, on_delete=models.SET_NULL, null=True)
    Pin = models.CharField(max_length=6, default=000000)


class Order(models.Model):
    Order_ID = models.AutoField(primary_key=True)
    Order_Customer_ID = models.ForeignKey(
        Profile, on_delete=models.PROTECT, null=True)
    Order_Address = models.ForeignKey(
        Address, on_delete=models.PROTECT, null=True)
    Order_Restaurant_ID = models.ForeignKey(
        Restaurant, on_delete=models.PROTECT, null=True)
    Order_Delivery_ID = models.ForeignKey(
        Delivery, on_delete=models.PROTECT, null=True)
    Order_Status = models.IntegerField(MaxValueValidator(5), null=True)
    Order_Time = models.DateTimeField(default=timezone.now, null=True)
    Order_Total_Price = models.IntegerField(default=0, null=True)


class Item(models.Model):
    Item_ID = models.AutoField(primary_key=True)
    Item_Order_ID = models.ForeignKey(
        Order, on_delete=models.CASCADE, null=True)
    Item_Food_ID = models.ForeignKey(Food, on_delete=models.CASCADE)
    Item_Quantity = models.IntegerField(MaxValueValidator(10))
    Item_Price = models.IntegerField(default=0)


class CartItems(models.Model):
    Cart_ID = models.AutoField(primary_key=True)
    Cart_Customer_ID = models.ForeignKey(Profile, on_delete=models.CASCADE)
    Cart_Food_ID = models.ForeignKey(Food, on_delete=models.CASCADE)
    Quantity = models.IntegerField(MaxValueValidator(5), null=True)

Customers/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from Customers.models import Profile, Address, Area


# Form for Signing Up.
class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)


# Takes other information of a user.
class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('Customer_First_Name', 'Customer_Last_Name',
                  'Customer_Phone_Number')


# Form to get user's address.
class AddressInfoForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ('Home', 'Street', 'city', 'area', 'Pin')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['area'].queryset = Area.objects.none()
        print(self.fields['area'].queryset)

        if 'city' in self.data:
            try:
                city_id = int(self.data.get('city'))
                self.fields['area'].queryset = Area.objects.filter(
                    city_id=city_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty city queryset
        elif self.instance.pk:
            self.fields['area'].queryset = self.instance.city.area_set.order_by(
                'name')


class CustomUserEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('Customer_First_Name', 'Customer_Last_Name',
                  'Customer_Phone_Number')

Customers/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from Restaurants.models import Restaurant, Food, FoodCategory
from .forms import SignUpForm, UserProfileInfoForm, AddressInfoForm, CustomUserEditForm
from .models import Address, Profile, CartItems, Item, Order, Area
from .tokens import account_activation_token

cuisines = ['Lunch', 'Brunch', 'Dinner']


@login_required(login_url='Main_index')
def index(request):
    vals = Address.objects.filter(
        Customer_ID=Profile.objects.get(user=request.user))
    pic = Profile.objects.get(user=request.user)
    context = {'vals': vals, 'pic': pic}
    return render(request, 'Customers/index.html', context=context)


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('Customers/emailver.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return render(request, 'Customers/checkemail.html')
        else:
            context = {'form': form, }
            return render(request, 'Customers/signup.html', context=context)
    else:
        form = SignUpForm()
        context = {'form': form, }
    return render(request, 'Customers/signup.html', context=context)


@login_required(login_url='Cus_login')
def profile_page(request):
    if request.method == 'POST':
        profile_form = UserProfileInfoForm(data=request.POST)
        address_form = AddressInfoForm(data=request.POST)
        # print(form)
        if profile_form.is_valid() and address_form.is_valid():
            profile = profile_form.save(commit=False)
            address = address_form.save(commit=False)
            profile.user = request.user
            profile.save()
            address.Customer_ID = Profile.objects.get(user=request.user)
            address.save()
            return redirect('http://127.0.0.1:8000/customer')
        elif not profile_form.is_valid():
            print(profile_form.errors)
        else:
            return render(request, 'customers/profile.html',
                          {'Profile_form': profile_form, 'address_form': address_form})
    else:
        profile_form = UserProfileInfoForm()
        address_form = AddressInfoForm()
    return render(request, 'customers/profile.html', {'Profile_form': profile_form, 'address_form': address_form})


def load_areas(request):
    city_id = request.GET.get('city')
    areas = Area.objects.filter(city_id=city_id).order_by('name')
    return render(request, 'Customers/area_dropdown_list_options.html', {'areas': areas})


def loginform(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if Profile.objects.filter(user=user).exists():
                return redirect('http://127.0.0.1:8000/customer')
            else:
                return redirect('http://127.0.0.1:8000/customer/profile')
        else:
            print(form.errors)
            contexts = {'form': form}
            return render(request, 'Customers/login.html', context=contexts)
    else:
        form = AuthenticationForm()
        context = {'form': form}
        return render(request, 'Customers/login.html', context=context)


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return render(request, 'Customers/After_Activation.html')
    else:
        return HttpResponse('Activation link is invalid!')


@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to FoodBuggy.
    return redirect('http://127.0.0.1:8000/')


def categories(request):
    context = {'cuisines': cuisines, }
    return render(request, 'Customers/categories.html', context)


@login_required(login_url='Cus_login')
def restaurants(request):
    global res_id
    if request.GET.get('res_id'):
        res_id = request.GET.get('res_id')
        return redirect('http://127.0.0.1:8000/customer/res_info')
    else:
        global data_address
        data_address = request.POST['area']
        filter_res = Restaurant.objects.filter(
            area__name=Address.objects.get(pk=data_address).area.name)
        address = Address.objects.get(pk=data_address).area.name
        context = {'filter_res': filter_res, 'data': address}
        return render(request, 'Customers/filter_res.html', context=context)


@login_required(login_url='Cus_login')
def res_info(request):
    data = Food.objects.filter(Food_Res_ID=res_id).order_by('Food_ID')
    rest_data = Restaurant.objects.all()
    catg_data = FoodCategory.objects.all()
    context = {'data': data, 'rest_data': rest_data, 'catg_data': catg_data}
    return render(request, 'Customers/res_info.html', context=context)


@login_required(login_url='Cus_login')
def add_address(request):
    if request.method == 'POST':
        address_form = AddressInfoForm(data=request.POST)
        if address_form.is_valid():
            address = address_form.save(commit=False)
            address.Customer_ID = Profile.objects.get(user=request.user)
            address.save()
            return redirect('http://127.0.0.1:8000/customer')
        else:
            context = {'address_form': address_form}
            return render(request, 'Customers/add_address.html', context=context)
    else:
        address_form = AddressInfoForm(data=request.POST)
        context = {'address_form': address_form}
        return render(request, 'Customers/add_address.html', context=context)


@login_required(login_url='Cus_login')
def add_to_cart(request):
    if request.method == 'POST':
        Food_ID = request.POST.get('Food ID')
        cart_object = CartItems()
        cart_object.Cart_Customer_ID = Profile.objects.get(user=request.user)
        cart_object.Cart_Food_ID = Food.objects.get(Food_ID=Food_ID)
        cart_object.Quantity = int(request.POST.get('Quantity'))
        if cart_object.Quantity > 0:
            cart_object.save()
        #        my_dict = {'items': CartItems.objects.filter(Cart_Customer_ID=Profile.objects.get(user=request.user))}
        return redirect('Cus_resinfo')


@login_required(login_url='Cus_login')
def cart(request):
    items = CartItems.objects.filter(
        Cart_Customer_ID=Profile.objects.get(user=request.user))
    context = {'items': items}
    return render(request, 'Customers/cart.html', context=context)


@login_required(login_url='Cus_login')
def delete(request):
    Cart_ID = request.POST.get('delete')
    CartItems.objects.get(Cart_ID=Cart_ID).delete()
    return redirect('Cus_cart')


@login_required(login_url='Cus_login')
def receipt(request):
    c_items = CartItems.objects.filter(
        Cart_Customer_ID=Profile.objects.get(user=request.user))
    if c_items:
        order = Order()
        order.save()
        for c_item in c_items:
            item = Item()
            item.Item_Food_ID = c_item.Cart_Food_ID
            item.Item_Order_ID = Order.objects.get(Order_ID=order.Order_ID)
            item.Item_Quantity = c_item.Quantity
            item.Item_Price = (c_item.Cart_Food_ID.Food_Price -
                               (c_item.Cart_Food_ID.Food_Discount * 100 /
                                c_item.Cart_Food_ID.Food_Price)) * c_item.Quantity
            item.save()

        items = Item.objects.filter(Item_Order_ID=order.Order_ID)
        for item in items:
            order.Order_Customer_ID = Profile.objects.get(user=request.user)
            order.Order_Restaurant_ID = item.Item_Food_ID.Food_Res_ID
            order.Order_Address = Address.objects.get(pk=data_address)
            order.Order_Status = 1
            order.save()
            break
        for item in items:
            order.Order_Total_Price += item.Item_Price
        order.save()
        c_items.delete()
        context = {'order': order, 'items': order.item_set.all()}
        return render(request, 'Customers/receipt.html', context=context)
    else:
        return redirect('Cus_index')


@login_required(login_url='Cus_login')
def edit_profile(request):
    instance = Profile.objects.get(user=request.user)
    form = CustomUserEditForm(request.POST or None, instance=instance)
    if form.is_valid():
        form.save()
        return redirect('Main_index')
    return render(request, 'Customers/edit_profile.html', {'form': form})


@login_required(login_url='Cus_login')
def show_profile(request):
    show = Profile.objects.get(user=request.user)
    add = Address.objects.filter(Customer_ID__user=request.user)
    print(add)

Customers/templates/Customers/After_Activation.html
<!DOCTYPE HTML>
<html>
{% load staticfiles %}
<head>
    <title>After Activating Mail</title>
    <link href="{% static 'css/style3.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords"
          content="Reset Password Form Responsive, Login form web template, Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design"/>
    <link href='//fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900' rel='stylesheet' type='text/css'>
    <link rel="shortcut icon" type="image/png" href="{% static 'food-logos.jpg' %}">
</head>

<body style="background-color:grey">
<div class="elelment">
    <div class="element-main" style="width: 50%;font-family: sans-serif;font-size: 20px">
        <p>
            Thank you for your email confirmation........!
        </p>
        <center>
            <span>→ </span> <a href="{% url 'Main_index' %}" style="color:#0086E5">Login</a><span
                style="font-size:17px">   here</span>
        </center>
    </div>
</div>
</body>
</html>

Customers/templates/Customers/add_address.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>

    <meta charset="UTF-8">
    <title>Add new address</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="{% static  "css/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static  "css/font-awesome.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static  "css/main1.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static  "css/util.css" %}">

    <link rel="shortcut icon" type="image/png" href="{% static 'food-logos.jpg' %}">
</head>
<body>

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <div class="login100-pic js-tilt" data-tilt>
                <img src="{% static "img-01.png" %}" alt="IMG">
            </div>

            <form class="login100-form validate-form" method="POST" id="AddressForm"
                  data-areas-url="{% url 'Cus_ajax_load_areas' %}" action="{% url "add_address" %}">
                {% csrf_token %}
                <span class="login100-form-title">
                        Add address
					</span>
                {% for field in address_form %}
                    {{ field.label_tag }}<br>
                    <div class="wrap-input100 validate-input input100">
                        {{ field }}
                        <span class="focus-input100"></span>
                    </div>
                {% endfor %}

                <div class="container-login100-form-btn">
                    <button class="login100-form-btn" type="submit" value="signup">
                        Submit
                    </button>
                </div>

                <div class="text-center p-t-12">
                    {% if user.is_authenticated %}
                        <a class="txt2" href="{% url 'logout' %}">
                            Log out
                        </a>
                    {% else %}
                    {% endif %}
                    <span class="txt1">
							here...
						</span>
                </div>

            </form>
        </div>
    </div>
</div>
</body>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_city").change(function () {
        var url = $("#AddressForm").data("areas-url");  // get the url of the `load_cities` view
        var cityId = $(this).val();  // get the selected country ID from the HTML input
        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
                'city': cityId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_area").html(data);  // replace the contents of the city input with the data that came from the server
            }
        });

    });
</script>

</html>

Customers/templates/Customers/area_dropdown_list_options.html
<option value="">---------</option>
{% for area in areas %}
    <option value="{{ area.pk }}">{{ area.name }}</option>
{% endfor %}

Customers/templates/Customers/checkemail.html
<!DOCTYPE HTML>
<html>
{% load staticfiles %}
<head>
    <title>After Activating Mail</title>
    <link href="{% static 'css/style3.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords"
          content="Reset Password Form Responsive, Login form web template, Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design"/>
    <link href='//fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900' rel='stylesheet' type='text/css'>
    <link rel="shortcut icon" type="image/png" href="{% static 'food-logos.jpg' %}">
</head>
<body style="background-color:grey">
<div class="elelment">
    <div class="element-main" style="width: 50%;font-family: sans-serif;font-size: 20px">
		<pre>
            Please confirm your email address to complete the registration    </pre>
        <center>
            <span>.    </span> <a href="https://mail.google.com/mail/" style="color:#0086E5"><img
                src="{% static 'images/icons8-google-48.png' %}"> </a>
            <span>.    </span><a href="https://login.yahoo.com/" style="color:#0086E5"><img
                src="{% static 'images/icons8-yahoo-48.png' %}"></a>
            <span>.    </span><a href="https://login.live.com/" style="color:#0086E5"><img
                src="{% static 'images/icons8-microsoft-outlook-48.png' %}"></a></center>
    </div>
</div>
</body>
</html>

Customers/templates/Customers/edit_profile.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>

    <meta charset="UTF-8">
    <title>Edit Profile</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="{% static  "css/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static  "css/font-awesome.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static  "css/main1.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static  "css/util.css" %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'food-logos.jpg' %}">
</head>
<body>
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <div class="login100-pic js-tilt" data-tilt>
                <img src="{% static "img-01.png" %}" alt="IMG">
            </div>
            <form class="login100-form validate-form" method="POST" action="{% url "Cus_edit_profile" %}">
                {% csrf_token %}
                <span class="login100-form-title">
                    Edit Profile
                </span>
                {% for field in form %}
                    {{ field.label_tag }}<br>
                    <div class="wrap-input100 validate-input input100">
                        {{ field }}
                        <span class="focus-input100"></span>
                    </div>
                {% endfor %}
                {% if form.errors %}
                    <p style="font-size: 12px;color: red">{{ form.errors.Customer_Phone_Number }}
                        please make sure to add +91 before</p>
                {% endif %}
                <div class="container-login100-form-btn">
                    <button class="login100-form-btn" type="submit" value="signup">
                        Submit
                    </button>
                </div>
                <div class="text-center p-t-12">
                    {% if user.is_authenticated %}
                        <a class="txt2" href="{% url 'logout' %}">
                            Log out
                        </a>
                    {% else %}
                    {% endif %}
                    <span class="txt1">
                        here...
                    </span>
                </div>
            </form>
        </div>
    </div>
</div>
</body>
</html>

Customers/templates/Customers/profile.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>Profile</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static  "css/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static  "css/font-awesome.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static  "css/main1.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static  "css/util.css" %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'food-logos.jpg' %}">
</head>
<body>
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <div class="login100-pic js-tilt" data-tilt>
                <img src="{% static "img-01.png" %}" alt="IMG">
            </div>

            <form class="login100-form validate-form" method="POST" id="AddressForm"
                  data-areas-url="{% url 'Cus_ajax_load_areas' %}" action="{% url "Cus_profile" %}">
                {% csrf_token %}
                <span class="login100-form-title">
                    User Profile
                </span>
                {% for field in Profile_form %}
                    {{ field.label_tag }}<br>
                    <div class="wrap-input100 validate-input input100">
                        {{ field }}
                        <span class="focus-input100"></span>
                    </div>
                {% endfor %}
                {% for field in address_form %}
                    {{ field.label_tag }}<br>
                    <div class="wrap-input100 validate-input input100">
                        {{ field }}
                        <span class="focus-input100"></span>
                    </div>
                {% endfor %}
                {% if Profile_form.errors %}
                    <p style="font-size: 12px;color: red">{{ Profile_form.errors.Customer_Phone_Number }}
                        please make sure to add +91 before</p>
                {% endif %}
                <div class="container-login100-form-btn">
                    <button class="login100-form-btn" type="submit" value="signup">
                        Submit
                    </button>
                </div>
                <div class="text-center p-t-12">
                    {% if user.is_authenticated %}
                        <a class="txt2" href="{% url 'logout' %}">
                            Log out
                        </a>
                    {% else %}
                    {% endif %}
                    <span class="txt1">
                        here...
                    </span>
                </div>
            </form>
        </div>
    </div>
</div>
</body>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_city").change(function () {
        var url = $("#AddressForm").data("areas-url");  // get the url of the `load_cities` view
        var cityId = $(this).val();  // get the selected country ID from the HTML input
        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
                'city': cityId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_area").html(data);  // replace the contents of the city input with the data that came from the server
            }
        });
    });
</script>

</html>

Customers/templates/Customers/receipt.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <title>Invoice letter</title>
    <link rel="stylesheet" href="{% static "css/style34.css" %}" media="all"/>
</head>

<body>
<header class="clearfix">
    <div id="company">
        <h2 class="name">Food Buggy</h2>
    </div>
</header>
<main>
    <div id="details" class="clearfix">
        <div id="client">
            <div class="to">INVOICE TO:</div>
            <h2 class="name">{{ order.Order_Customer_ID.Customer_First_Name }} {{ order.Order_Customer_ID.Customer_Last_Name }}</h2>
            <div class="address"></div>
            <div>{{ order.Order_Customer_ID.Customer_Phone_Number }}</div>
            <div class="email">{{ order.Order_Customer_ID.Customer_Email }}</div>
            <div class="date">Date and time of Invoice: {{ order.Order_Time }}</div>
        </div>
    </div>
    <table border="0" cellspacing="0" cellpadding="0">
        <thead>
        <tr>
            <th class="desc">Description</th>
            <th class="unit">Unit Price</th>
            <th class="qty">Quantity</th>
            <th class="total">Total</th>
        </tr>
        </thead>
        <tbody>
        {% for item in items %}
            <tr>
                <td class="desc"><h3>{{ item.Item_Food_ID.Food_Name }}</h3></td>
                <td class="unit">{{ item.Item_Food_ID.Food_Price }}</td>
                <td class="qty">{{ item.Item_Quantity }}</td>
                <td class="total">{{ item.Item_Price }}</td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>

            <td colspan="3">GRAND TOTAL</td>
            <td>Rs. {{ order.Order_Total_Price }}</td>
        </tr>
        </tfoot>
    </table>
    <div id="thanks">Return to <a href="{% url 'Main_index' %}">homepage</a> Thank you!</div>
</main>
<footer>
    Invoice was created on a computer and is valid without the signature and seal.
</footer>
</body>
</html>