D_delivery/urls.py
from django.urls import path
from . import views
app_name = 'D_delivery'
urlpatterns = [
    path('', views.result, name='D_delivery.result'),
    path('result1/', views.result1, name='result1'),
    ]

Delivery/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.index, name='Del_index'),
    path('signup/', views.signup, name='Del_signup'),
    path('profile/', views.profile_page, name='Del_profile'),
    path('ajax/load-areas/', views.load_areas, name='Del_ajax_load_areas'),
    re_path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='Del_activate'),
    path('del_orders/', views.del_orders, name='Del_orders'),
    path('edit/', views.edit_profile, name='Del_edit_profile'),
]

R_m/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('Res_Man.urls')),
]

Res_Man/urls.py
from django.contrib import admin
from django.urls import path
from R_m import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('snippets/', views.snippet_list),
    path('snippets/<int:pk>/', views.snippet_detail),

]

search/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('S_search/', include('S_search.urls', namespace='S_search')),
]

D_delivery/models.py
from django.db import models

# Create your models here.


class Customer(models.Model):
    Customer_ID = models.CharField(max_length=150)


class Address(models.Model):
    Address_ID = models.CharField(max_length=150)


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    address = models.ForeignKey(Address, on_delete=models.PROTECT)
    Order_ID = models.CharField(max_length=150, primary_key=True)
    Discount = models.FloatField(null=False)
    Total_Price = models.FloatField(null=False)
    Status = models.BooleanField(null=False)

D_delivery/views.py
from django.shortcuts import render

# Create your views here.
from django .http import HttpResponse,HttpResponseRedirect,HttpResponsePermanentRedirect
from django .urls import reverse
from .models import Address, Customer, Order


def result1(request):
    if request.method=='POST':
        v = request.POST['Delivered']
        order = Order.objects.get(pk=v)
        order.Status=True
        order.save()
        objs = Order.objects.all()
        context = {'objs': objs}
    return render(request,'D_delivery/display.html',context=context)


def result(request):
    a = {"Order1": {'Customer_ID': "4365431", 'Order_ID': '1343554', 'Address_ID': '3531', 'Total_Price': 25,
                    'Discount': 3, 'Status': False},
         "Order2": {'Customer_ID': "533451", 'Order_ID': 'r134556', 'Address_ID': '45532', 'Total_Price': 25,
                    'Discount': 3, 'Status': False}}
    for k in ['Order1','Order2']:
        customerid = a[k]['Customer_ID']
        orderid = a[k]['Order_ID']
        addressid = a[k]['Address_ID']
        totalprice = a[k]['Total_Price']
        discount = a[k]['Discount']
        status = a[k]['Status']
        address = Address.objects.create(Address_ID=addressid)
        customer = Customer.objects.create(Customer_ID=customerid)
        Order.objects.create(customer=customer, address=address, Order_ID=orderid, Total_Price=totalprice, Discount=discount, Status=status)
    objs = Order.objects.all()
    context = {'objs': objs}
    return render(request, 'D_delivery/display.html', context=context)

D_delivery/templates/D_delivery/display.html
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>Orders Received</title>


</head>

<body>

  <h1><span class="yellow">Orders Received</pan></h1>

<table class="container">
	<head>
		<tr bgcolor="#dc143c">
			<th><h1>Customer ID</h1></th>
			<th><h1>Address ID</h1></th>
			<th><h1>Order ID</h1></th>
			<th><h1>Discount</h1></th>
			<th><h1>Total Price</h1></th>
			<th><h1>Order Status</h1></th>
		</tr>
	</head>
	<body>
        {% for obj in objs %}
		<tr>
			<td>{{ obj.customer.Customer_ID }}</td>
			<td>{{ obj.address.Address_ID }}</td>
			<td>{{ obj.Order_ID }}</td>
			<td>{{ obj.Discount }}</td>
			<td>{{ obj.Total_Price }}</td>
            <td>
                <form action="{% url 'D_delivery:result1' %}" method="post">
                    {%  csrf_token %}
                    {% if obj.Status == False %}
                                            <button type="submit" name="Delivered" value={{ obj.Order_ID }}>{{ obj.Status }}</button>

                        {% else %}
                                            {{ obj.Status }}

                    {% endif %}
                </form>
            </td>
		</tr>
        {% endfor %}
	</body>
</table>



</body>

</html>

D_delivery/templates/D_delivery/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order</title>
</head>
<body>
<h1>ORDER</h1>>
<form action="result/" method="post">
    {%  csrf_token %}
    Order_ID:<br>
    <input type="text" name="Order_ID" id="Order_ID"><br>
    Customer_ID:<br>
    <input type="text" name="Customer_ID" id="Customer_ID"><br>
    Address_ID:<br>
    <input type="text" name="Address_ID" id="Address_ID"><br>
    Discount:<br>
    <input type="text" name="Discount" id="Discount"><br><br>
    Total_Price:<br>
    <input type="text" name="Total_Price" id="Total_Price"><br><br>
    <button type="submit">Submit</button>
</form>

</body>
</html>